Fix/graph not clickable
NiranjanBK/Investtech pull request #27
Opened 2022-10-20 10:55 UTC by arslancreo

2022-10-20 11:03 UTC, arslancreo commented
![image_123986672](https://user-images.githubusercontent.com/115970674/196931911-bf80af5f-9dfd-490d-b5d4-f485dc636878.JPG)
![image_123986672](https://user-images.githubusercontent.com/115970674/196931945-1e1bc1ad-2e50-4f86-abbb-71752dff5bca.JPG)
![image_123986672](https://user-images.githubusercontent.com/115970674/196931983-466287f1-ca66-4eec-8934-4ace8ed8ef1f.JPG)
![image_123986672](https://user-images.githubusercontent.com/115970674/196932024-e1eb0dc6-d2b8-47ed-9711-f1c039d062e6.JPG)

2022-10-20 13:36 UTC, KamathVishak96 requested changes

2022-10-20 13:36 UTC, KamathVishak96 commented on lib/ui/favourites/chart_view.dart
> +          aspectRatio: 1080/648,
Format this code. There should be Space between `/` and the Numbers. Running Cmd + Opt + L on Android studio formats the whole file.

2022-10-21 05:35 UTC, KamathVishak96 approved these changes

2022-10-21 05:35 UTC, merged